### ISSUE TITLE
Deployment without probes doesn't show full log

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/kubedog#282]
On successful `converge` full log of the Deployment's Pod is not showed if the Pod doesn't have any probes.

To reproduce, `werf converge` this manifest:
```yaml
# .helm/templates/test.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: ubuntu:22.04
          command:
            - sh
            - -ec
            - |
              echo POD STARTED
              tail -f /dev/null
```

Will result in no "POD STARTED" log line in `werf converge` log. But adding
```yaml
          startupProbe:
            exec:
              command: ["/bin/sleep", "5"]
            timeoutSeconds: 10
```
to the deployment makes the log line appear in `werf converge` log, as expected.
