### ISSUE TITLE
Failing Pod (of a Deployment) doesn't show its logs after Pod's container restarted due to failure

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/kubedog#283]
To reproduce, run `werf converge` with this manifest:
```yaml
# .helm/templates/test.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: ubuntu:22.04
          command:
            - sh
            - -ec
            - |
              echo date: $(date) && false
```
This will show `date: <current date>` log line in `werf converge` log only once, but it should be twice.
